version: "3.9"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - local-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - local-network

networks:
  default:
    # Use a custom driver
    driver: bridge
  local-network:
    driver: bridge